project:
  type: book
  output-dir: docs

book:
  title: "Mathematical Modelling Encyclopedia"
  author:
    - name: Marc Choisy
    - name: Thinh Ong
      url: https://thinhong.github.io
      orcid: 0000-0001-6772-9291
    - name: Tuyen Huynh
    - name: Nguyen Pham
    - name: Lam Nguyen
  chapters:
    - index.qmd
    - intro.qmd
    - jargons.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



