# Jargons

## Probability, rate, proportion^[by [Marc](https://github.com/thinhong/cpp_training/issues/12)]

A **probability** is between 0 and 1 and is the chance (or risk) that an event (death, infection, etc...) happens. In general this probability is defined ***over a period of time*** and will necessarily increase as the duration of this period of time increases.

A **rate** is an instantaneous measure of change per unit time [@selvin2004], the frequency at which an event happens. It is thus always positive and always expressed per unit of time (like speed km/h or m/s). Rate can be \> 1. Mathematically, it is the limit of the above-mentioned probability when the duration of the period of time tends towards zero (i.e. very small, i.e. instantaneous measure).

A **proportion** is the ratio of a numerator and a denominator and by definition is between 0 and 1.

What is the difference between **proportion** and **probability**? Consider this example:

A bag is filled with 100 balls, of which 30 are [blue]{style="color: blue"} and 70 are [green]{style="color: green"}. Without looking, you pull out a ball, write down the color, then put it back to the bag. You repeat the action 10,000 times. The number of times you pulled out a [blue]{style="color: blue"} ball is 3011.

- The proportion of [blue]{style="color: blue"} balls in the bag is 30/100 = 0.3
- A **Frequentist** say: The probability of pulling out a [blue]{style="color: blue"} ball is 3011/10,000 = 0.3011 because you did experiment in long-run (10,000 times).
- A **Bayesian** say: The probability of pulling out a [blue]{style="color: blue"} ball is 0.3 because you know that you have a proportion of 0.3 [blue]{style="color: blue"} balls in the bag.

## Discrete and continuous

## Dynamic and static

## Deterministic and stochastic

## Mechanistic model and statistic model
